name: cryptotracker
description: A new Flutter project for tracking crypto prices.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
# pubspec.yaml එකේ environment කොටසට පල්ලෙහායින් මේක දාන්න
environment:
  sdk: '>=3.0.0 <4.0.0'

# අලුතින්ම මේ පේළි දෙක එකතු කරන්න:
flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
